# -*- coding: utf-8 -*-
"""Hackathon3_batabase_creation.file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbKDGhWntxiiVh-WYCVf1OWLuYjRV2hd
"""

import sqlite3
import random

conn = sqlite3.connect("placement.db")
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS placement_data")

cursor.execute("""
CREATE TABLE placement_data (
    student_id INTEGER,
    cgpa REAL,
    attendance_percentage INTEGER,
    projects_count INTEGER,
    coding_score INTEGER,
    aptitude_score INTEGER,
    mock_interview_score INTEGER,
    internship_experience INTEGER,
    communication_score INTEGER,
    placement_status INTEGER
)
""")

for i in range(600):

    student_id = 1000 + i

    coding = random.randint(30, 100)
    aptitude = random.randint(30, 100)
    mock = random.randint(30, 100)
    communication = random.randint(30, 100)
    projects = random.randint(0, 6)

    cgpa = round(random.uniform(5.5, 9.8), 2)
    attendance = random.randint(60, 100)
    internship = random.choice([0,1])

    # Realistic weighted score
    base_score = (
        coding * 0.22 +
        aptitude * 0.18 +
        mock * 0.22 +
        communication * 0.22 +
        projects * 4 +
        cgpa * 2
    )

    # Add noise (IMPORTANT → makes data real)
    noise = random.uniform(-15, 15)

    final_score = base_score + noise

    placement = 1 if final_score > 65 else 0

    cursor.execute("""
    INSERT INTO placement_data VALUES (?,?,?,?,?,?,?,?,?,?)
    """, (
        student_id,
        cgpa,
        attendance,
        projects,
        coding,
        aptitude,
        mock,
        internship,
        communication,
        placement
    ))

conn.commit()
conn.close()

print("✅ Realistic Synthetic Dataset Generated")

from google.colab import files
files.download("placement.db")