# -*- coding: utf-8 -*-
"""Hackathon_3_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnnZjIjBKwMSgDTtdOvq6lMkNK0RhNfR
"""

import sqlite3
import pandas as pd

# Connect to database
conn = sqlite3.connect("placement.db")

# Read table into dataframe
df = pd.read_sql("SELECT * FROM placement_data", conn)

# Close connection
conn.close()

# Check data
df.head()

import pandas as pd
import sqlite3

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib

import seaborn as sns
import matplotlib.pyplot as plt

conn = sqlite3.connect("placement.db")

df = pd.read_sql("SELECT * FROM placement_data", conn)

conn.close()

print(df.head())

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

df["communication_group"] = pd.cut(
    df["communication_score"],
    bins=[0,40,60,80,100],
    labels=["Low","Medium","Good","Excellent"]
)

df["mock_group"] = pd.cut(
    df["mock_interview_score"],
    bins=[0,40,60,80,100],
    labels=["Low","Medium","Good","Excellent"]
)

df["coding_group"] = pd.cut(
    df["coding_score"],
    bins=[0,40,60,80,100],
    labels=["Low","Medium","Good","Excellent"]
)

df["aptitude_group"] = pd.cut(
    df["aptitude_score"],
    bins=[0,40,60,80,100],
    labels=["Low","Medium","Good","Excellent"]
)

sns.barplot(x="communication_group", y="placement_status", data=df)
plt.title("Communication Level vs Placement Rate")
plt.show()

sns.barplot(x="mock_group", y="placement_status", data=df)
plt.title("Mock Interview Level vs Placement Rate")
plt.show()

sns.barplot(x="coding_group", y="placement_status", data=df)
plt.title("Coding Level vs Placement Rate")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x="placement_status", data=df)
plt.title("Placement Distribution")
plt.show()

# =========================
# FEATURE SELECTION (HIGH CORRELATION FEATURES ONLY)
# =========================

X = df[[
    "coding_score",
    "aptitude_score",
    "mock_interview_score",
    "communication_score",
    "projects_count"
]]

y = df["placement_status"]

print("\nSelected Features:")
print(X.columns)


# =========================
# TRAIN TEST SPLIT
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTrain Test Split Done")


# =========================
# TRAIN LOGISTIC REGRESSION MODEL
# =========================

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("\nModel Training Completed")


# =========================
# TEST MODEL PERFORMANCE
# =========================

y_pred = model.predict(X_test)

print("\nModel Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


# =========================
# SAVE MODEL
# =========================

joblib.dump(model, "placement_model.pkl")

print("\nModel Saved Successfully as placement_model.pkl")

joblib.dump(model, "placement_model.pkl")
print("Model Saved")

from google.colab import files
files.download("placement_model.pkl")